code --install-extension 42Crunch.vscode-openapi
code --install-extension alex-young.pm2-explorer
code --install-extension alexkrechik.cucumberautocomplete
code --install-extension AlexShenVSCode.alex-s-dark-theme
code --install-extension Arjun.swagger-viewer
code --install-extension atlassian.atlascode
code --install-extension burkeholland.simple-timer
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension dbaeumer.vscode-eslint
code --install-extension dionmunk.vscode-notes
code --install-extension DotJoshJohnson.xml
code --install-extension dracula-theme-pro.theme-dracula-pro
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension eg2.vscode-npm-script
code --install-extension esbenp.prettier-vscode
code --install-extension firsttris.vscode-jest-runner
code --install-extension foxundermoon.shell-format
code --install-extension GitHub.codespaces
code --install-extension GitHub.vscode-pull-request-github
code --install-extension GitLab.gitlab-workflow
code --install-extension JakeBecker.elixir-ls
code --install-extension joshbolduc.commitlint
code --install-extension mrmlnc.vscode-scss
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode-remote.vscode-remote-extensionpack
code --install-extension ms-vscode.makefile-tools
code --install-extension ms-vscode.remote-explorer
code --install-extension ms-vscode.remote-server
code --install-extension oderwat.indent-rainbow
code --install-extension PKief.material-icon-theme
code --install-extension rafamel.subtle-brackets
code --install-extension redhat.vscode-yaml
code --install-extension rvest.vs-code-prettier-eslint
code --install-extension shakram02.bash-beautify
code --install-extension sibiraj-s.vscode-scss-formatter
code --install-extension stylelint.vscode-stylelint
code --install-extension techer.open-in-browser
code --install-extension vintharas.learn-vim
code --install-extension wayou.vscode-todo-highlight
code --install-extension wmaurer.change-case
code --install-extension xabikos.JavaScriptSnippets
code --install-extension yaelguilloux.vscode-commit-prompt
code --install-extension yzhang.markdown-all-in-one
