#!/usr/bin/env sh

# source is https://github.com/slavistan/howto-lf-image-previews/blob/master/lf-cleaner

cat <<EOF | paste -s -d '' > "$LF_FIFO_UEBERZUG"
{
"action": "remove",
"identifier": "lf-preview"
}
EOF
